"""
STL mesh based feature detection.

These detectors operate on triangle meshes generated by trimesh.
"""

from .holes import detect_mesh_holes
from .bosses import detect_mesh_bosses
from .ribs import detect_mesh_ribs
from .fillets import detect_mesh_fillets
from .chamfers import detect_mesh_chamfers

__all__ = [
    "detect_mesh_holes",
    "detect_mesh_bosses",
    "detect_mesh_ribs",
    "detect_mesh_fillets",
    "detect_mesh_chamfers",
]
