"""
STL mesh based feature detection.

These detectors operate on triangle meshes generated by trimesh.
"""

from .holes import detect_mesh_holes
from .bosses import detect_mesh_bosses
from .ribs import detect_mesh_ribs

__all__ = [
    "detect_mesh_holes",
    "detect_mesh_bosses",
    "detect_mesh_ribs",
]
